services:
  db:
    image: postgres:16
    container_name: impactcms-db
    environment:
      POSTGRES_USER: impact
      POSTGRES_PASSWORD: impact
      POSTGRES_DB: impactdb_dev
    ports:
      - "5432:5432"
    volumes:
      - impactcms_pgdata:/var/lib/postgresql/data

volumes:
  impactcms_pgdata: